name: Reusable Notebook Output Stripper

on:
  workflow_call: {}  # Enables other repos to call this workflow

permissions:
  contents: write  # Needed to commit and push back changes

jobs:
  clean_notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install tools
        run: |
          pip install nbstripout jupyter

      - name: Strip notebook outputs
        run: |
          find . -name '*.ipynb' -exec jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace --clear-output {} \;

      - name: Commit cleaned notebooks
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: auto-strip notebook outputs"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:master
