name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 12 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ### content
          SECTION_NAME: waka
          SYMBOL_VERSION: 1
          SHOW_LINES_OF_CODE: false
          SHOW_TOTAL_CODE_TIME: false
          SHOW_COMMIT: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_LANGUAGE: false
          SHOW_OS: false
          SHOW_PROJECTS: false
          SHOW_TIMEZONE: false
          SHOW_EDITORS: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_LOC_CHART: false
          # SHOW_SHORT_INFO: true
          ### commit
          # COMMIT_BY_ME: true
          COMMIT_MESSAGE: Updated with Dev Metrics
          COMMIT_EMAIL: action-bot@github.com
