name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "10 19 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ### content
          SECTION_NAME: waka
          SYMBOL_VERSION: 1
          # CODE_LANG: rust # optional
          # TIME_RANGE: last_7_days # optional
          # LANG_COUNT: 10 # optional
          SHOW_LINES_OF_CODE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_LANGUAGE: true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_TIMEZONE: true
          SHOW_EDITORS: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_SHORT_INFO: true
          ### commit
          COMMIT_BY_ME: true
          COMMIT_MESSAGE: Updated with Dev Metrics
          COMMIT_EMAIL: action-bot@github.com
